### ISSUE TITLE
npm package for 0.16.4 is missing sources

### ISSUE THREAD

**Issue by tyrasd** [luizbarboza/polyclip-ts#10]
The published package on npmjs.com is missing the compiled sources in `dist/` and `types/`. See see https://www.npmjs.com/package/polyclip-ts/v/0.16.4?activeTab=code, or do something like `npm install polyclip-ts && ls ./node_modules/polyclip-ts` to confirm.

**Comment by luizbarboza** [comment]
Fixed in version 0.16.5. Thanks for pointing out.
