### ISSUE TITLE
Discussing compatibility with polygon-clipping types

### ISSUE THREAD

**Issue by markstos** [luizbarboza/polyclip-ts#7]
I'm interested in having the Turf project replace `polygon-clipping` with tis library.  ( [related issue](https://github.com/Turfjs/turf/issues/2409#issuecomment-1461511072) ).

I've started on the work, but I'm also less experienced working with types and have run into some cases I'm not sure how to resolved. 

## Geom public vs private

The `polygon-clipping` library has a Geom type. This ibrary has it too, but it does not seem to exposed. Here's how the type is used by turf-union:

```
const geoms: polygonClipping.Geom[] = [];
```

_Can this module export the same type for compatibility?_

## number type vs Position type

`turf-union` has this code:

```javascript
 const unioned = polyclip.union(geoms[0], ...geoms.slice(1));
  if (unioned.length === 0) return null;
  if (unioned.length === 1) return polygon(unioned[0], options.properties);
```

There, `polygon` method comes from `@turf/helpers`

If I swap in `polyclip-ts`, I get this typing error with `npm run build`:

```
 Argument of type '(number[][] | null)[][]' is not assignable to parameter of type 'Position[][][]'.
```

How can this typing difference be smoothed over?

Thanks!

**Comment by dennemark** [comment]
If this allows swapping polygon-clipping in turf.js, i also would appreciate that this issue could be resolved.

**Comment by luizbarboza** [comment]
@markstos Version 1.16.4 now exports the `Geom` type and should also resolve the typing error.

**Comment by smallsaucepan** [comment]
@markstos FYI now investigating this from the Turf side. Do you still have some bandwidth to be involved? https://github.com/orgs/Turfjs/projects/2

**Comment by markstos** [comment]
@smallsaucepan I still have some interest in helping with this, although I don't have access to view the link you sent: https://github.com/orgs/Turfjs/projects/2

It returns 404 for me, but I think that's often how Github handles access-denied cases. 

It seems like if this project has resolved the typing issue, then I could pick up where I left off?

**Comment by markstos** [comment]
I see there was recent activity planning for Turfjs v7:
https://github.com/Turfjs/turf/pull/2607

**Comment by smallsaucepan** [comment]
Thanks @markstos. Sorry about project visibility. It's basically pulling together some clipping related bugs - [#2409](https://github.com/Turfjs/turf/issues/2409), [#2277](https://github.com/Turfjs/turf/issues/2277), [#2048](https://github.com/Turfjs/turf/issues/2048), and [#2588](https://github.com/Turfjs/turf/issues/2588).

At this point waiting for Turf v7 to make it out the door. Then we can look at working on issues like this for 7.1, 7.2, etc

**Comment by markstos** [comment]
7.0 is out now, so that question is answered. I'll proceed as time permits.

**Comment by smallsaucepan** [comment]
Sorry for not replying to your previous message @markstos. Yes, 7 is out now so let's carry on the discussion over at the Turf repo.
